version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subway
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul

# docker compose --build -up